### ISSUE TITLE
Design discussion: Enabling maximal customizability and adaptability of composite strategies

### ISSUE THREAD

**Issue by fkromer** [fkromer/rospbt#23]
This issue is for discussion of design choices for composite strategies (which can be potentially nested having more than 1 level of "leafs"). Getting the configuration is less a challenge than getting the strategies fully compatible with [Hypothesis adaption capabilities](https://hypothesis.readthedocs.io/en/latest/data.html#adapting-strategies). As example for the discussion we use the `std_msgs/Point` strategy ([docs.ros.org - geometry_msgs/Point](http://docs.ros.org/api/geometry_msgs/html/msg/Point.html)).

**Comment by fkromer** [comment]
@Zac-HD No worries. I'll continue somewhen the next evenings. Thx a lot.

**Comment by Zac-HD** [comment]
OK, I'm just going to do a stream-of-consciousness dump as I read [builtin_msg_field_types.py](https://github.com/fkromer/rospbt/blob/c9ef52cfa1e23dd8042d8f11da47f459580c97c8/rospbt/ros1/generators/builtin_msg_field_types.py):

- Constant literals always make me nervous.  I'd define `INT64_MIN_VALUE` as  `−1 * 2^63`, rather than `-9223372036854775808` - better to be obviously than non-obviously correct, and save the time readers will use to check for typos.
- You don't need to define `FLOAT64_MIN_VALUE` and `FLOAT64_MAX_VALUE`; Hypothesis only generates 64-bit floats in the first place.
- For strategies such as `int8()`, add a check that user-supplied bounds are in range.  This can be as simple as `assert INT8_MIN_VALUE <= min_value <= max_value <= INT8_MAX_VALUE`!  Never trusting user input can make life a lot easier later, and sprinkling this kind of assertion through internal code too is a habit which makes PBT more powerful.
- Docstrings: strategies don't shrink values, the underlying engine produces smaller examples from the strategy.  
- If you're generating HTML or other docs from the docstrings, I'd link to the ROS docs on the corresponding field from each strategy.  If they also use Sphinx you can use the `intersphinx` extension to get a nice markup for this.

Overall: a solid start!  I don't know how different ROS1 and ROS2 are, but it might be worth factoring out fundamentals like this into a shared section.

-------------

`notebooks/point.ipynb`:  I think you're over-complicating this.  Instead of passing kwargs with which to construct a strategy, in Hypothesis we simply make you pass a strategy directly.  For example:

```python
@composite
def point(draw, x=float64(), y=float64(), y=float64()):
    x_val, y_val, z_val = draw(x), draw(y), draw(z)
    # check that each value is valid for the respective field, e.g.
    assert isinstance(x_val, float), f'drew invalid x={x_val} from {x} for float64 field'
    # Obviously the check is more precise for sized integers!
    return _Point(x, y, z)
```

Customising one leaf of a deeply nested tree is kinda painful, but that's always going to be the case.  In Hypothesis, we just do our best to infer missing strategies, and trust that the user can assign parts to variables etc. if they really need to.  To some extent though, this kind of fiddly customisation really does indicate that PBT might be the wrong way to write the test in question.

-----------

I think this is off to a solid start!  The next things I'd do are:

1. Write strategies for more detailed message types.  These are the basic primitives that everything else is built on.
2. Write a function that can take a message type, and infer the corresponding strategy.  This is the key piece that will save your users a lot of time.  It *also* encourages high-quality code, by increasing the friction of functions that only accept *some* of the values representable by a message type.
3. Get users and listen to their feedback!  Probably a good idea to apply it to your own projects first, then ideally try it out at e.g. a makerspace where you can get live feedback, but at some point you've just got to release it into the wild and see what happens :smile: 

-------------

Feel free to ask about any of this, or just ping me again whenever you want another round of comments!

**Comment by fkromer** [comment]
Thanks a lot for the review!

> - Constant literals always make me nervous. I'd define INT64_MIN_VALUE as −1 * 2^63, rather than -9223372036854775808 - better to be obviously than non-obviously correct, and save the time readers will use to check for typos.
> - You don't need to define FLOAT64_MIN_VALUE and FLOAT64_MAX_VALUE; Hypothesis only generates 64-bit floats in the first place.

That's right.

> - For strategies such as int8(), add a check that user-supplied bounds are in range. This can be as simple as assert INT8_MIN_VALUE <= min_value <= max_value <= INT8_MAX_VALUE! Never trusting user input can make life a lot easier later, and sprinkling this kind of assertion through internal code too is a habit which makes PBT more powerful.

That's on my TODO list already. Sticking to an implementation like in the [Hypothesis NumPy extension `check_argument`](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/numpy.py#L82) should do the job.

> - Docstrings: strategies don't shrink values, the underlying engine produces smaller examples from the strategy.

Added to the TODO list.

> - If you're generating HTML or other docs from the docstrings, I'd link to the ROS docs on the corresponding field from each strategy. If they also use Sphinx you can use the intersphinx extension to get a nice markup for this.

Hyperlinking the ROS and ROS2 types is on my TODO list already as well. (ROS and ROS2 do not use `Sphinx` and using `intersphinx` is not possible.)

> Overall: a solid start! I don't know how different ROS1 and ROS2 are, but it might be worth factoring out fundamentals like this into a shared section.

You are totally right. I wanted to get the things done from a technical/implementation point of view first. As soon as I am sure which is shared, ROS1 only or ROS2 only this kind of refactoring is usually done in minutes. (But I am not sure right now that I did not miss something :wink: .)

> notebooks/point.ipynb: I think you're over-complicating this. Instead of passing kwargs with which to construct a strategy, in Hypothesis we simply make you pass a strategy directly. For example:

```
@composite
def point(draw, x=float64(), y=float64(), y=float64()):
    x_val, y_val, z_val = draw(x), draw(y), draw(z)
    # check that each value is valid for the respective field, e.g.
    assert isinstance(x_val, float), f'drew invalid x={x_val} from {x} for float64 field'
    # Obviously the check is more precise for sized integers!
    return _Point(x, y, z)
```

Ah, right :smiley: . Customizing is way easier and more convenient with your suggested design. As long as one modifies the check `assert isinstance(x_val, float), f'drew invalid x={x_val} from {x} for float64 field'` to also accept strategies in general it should even be possible to use adapted strategies for x, y and z like e.g. `x=float64().map(...)`, right?

I thought about to accept optional, callable keyword arguments like `x_map=map(...)` which would have been added to `x=float64().map(...)` to allow adaption of "leaf" strategies. Equivalent for `filter()` and `flatmap()`... But your design is way cleaner.

> Customising one leaf of a deeply nested tree is kinda painful, but that's always going to be the case. In Hypothesis, we just do our best to infer missing strategies, and trust that the user can assign parts to variables etc. if they really need to. To some extent though, this kind of fiddly customisation really does indicate that PBT might be the wrong way to write the test in question.

I think if (detailed) adaption of "leaf" strategies is required or not depends much on the property a user wants to check. E.g. in case of ROS there should not be any need to adapt strategies to check the property "ROS node still alive". However there could be observers for ROS node output data in the future which could assert in-range data. In this case a user would want to define input ranges by using adapting strategies. Therefore I would like to provide as much as possible adaptability and let the user decide how to use it.

> I think this is off to a solid start! The next things I'd do are:
> 
> 1.   Write strategies for more detailed message types. These are the basic primitives that everything else is built on.
> 2.    Write a function that can take a message type, and infer the corresponding strategy. This is the key piece that will save your users a lot of time. It also encourages high-quality code, by increasing the friction of functions that only accept some of the values representable by a message type.
> 3.    Get users and listen to their feedback! Probably a good idea to apply it to your own projects first, then ideally try it out at e.g. a makerspace where you can get live feedback, but at some point you've just got to release it into the wild and see what happens smile

I'll do so... :wink: 

> Feel free to ask about any of this, or just ping me again whenever you want another round of comments!

Thx a lot for your help! Would be great if you could help to solve the "adaptability" design issue (above). Then the most things should be clarified for now...

**Comment by Zac-HD** [comment]
> There are no docs specific to single types. ROS and ROS2 do not use Sphinx and using intersphinx is not possible.

Ouch - a wiki is better than nothing, but I wouldn't call it documentation :disappointed: (not versioned, untestable, etc).  A few "custom directives" for sphinx would be trivial to write (just a mapping of stubs to URL patterns) and might make linking easier?  Not urgent but good to know if you revisit later.

> Customizing is way easier and more convenient with your suggested design [all args are strategies]. As long as one modifies the check `assert isinstance(x_val, float)` to also accept strategies in general it should even be possible to use adapted strategies for x, y and z like e.g. `x=float64().map(...)`, right?

Yep, adapted strategies are just strategies to Hypothesis and will work as expected.  Note that the assertion is about the *value drawn from the strategy*, not the strategy itself - e.g. to ensure that you always get an in-range integer for a uint8 field - so this should *not* accept a strategy for `x_val`.  Of course `x` must be a strategy or `draw(x)` will fail loudly...

> I would like to provide as much as possible adaptability and let the user decide how to use it.

Agreed!  We have a couple of design tactics for this:

1. Provide a solid layer of basics.  Users with really weird edge cases can build their strategy up from primitives like `int8()` all the way to complex messages.
2. Provide some easy ways to compose them, which only need things spelled out for edge cases.  For example, `builds()` will use type hints to infer a strategy for missing required arguments - by analogy, users of rospbt would need to provide the chain of branches down to the leaf, but not the whole tree!  IMO you can't really do better than this without compromising usability for the majority of non-pathological cases.
3. Provide a magic top layer `from_message(msg, **kwargs)` that infers everything *except* strategies given in kwargs.  This is also the implementation for (2) if it goes well!  For example:  given a "move" message of a pair of points (start, end) which must have z>=0... `from_message(move, start=from_message(point, z=float64(min_value=0)), ...)`.  Note that in actual code I'd pull out a `positive_altitude_point` variable for easier reference!

So: adaptability first by composition and second by customisation, but never at the expense of the default case because that's where everyone will start, and where most time will be spent.

**Comment by fkromer** [comment]
>  A few "custom directives" for sphinx would be trivial to write (just a mapping of stubs to URL patterns) and might make linking easier? Not urgent but good to know if you revisit later.

I will use `intersphinx` to hyper link to Hypothesis docs (strategies, etc.). Would you guys consider to deploy versioned [hypothesis rtd docs](https://hypothesis.readthedocs.io/en/latest/index.html) for the major versions? According to the [Hypothesis Changelog](https://hypothesis.readthedocs.io/en/latest/changes.html#) linking to minor and patch versions would imply massive maintenance overhead :smile: .

> Note that the assertion is about the value drawn from the strategy, not the strategy itself - e.g. to ensure that you always get an in-range integer for a uint8 field - so this should not accept a strategy for x_val. Of course x must be a strategy or draw(x) will fail loudly...

Right. The assert is just fine.

> Agreed! We have a couple of design tactics for this:
>
> 1. Provide a solid layer of basics. Users with really weird edge cases can build their strategy up from primitives like int8() all the way to complex messages.
> 2. Provide some easy ways to compose them, which only need things spelled out for edge cases. For example, builds() will use type hints to infer a strategy for missing required arguments - by analogy, users of rospbt would need to provide the chain of branches down to the leaf, but not the whole tree! IMO you can't really do better than this without compromising usability for the majority of non-pathological cases.
> 3. Provide a magic top layer from_message(msg, **kwargs) that infers everything except strategies given in kwargs. This is also the implementation for (2) if it goes well! For example: given a "move" message of a pair of points (start, end) which must have z>=0... from_message(move, start=from_message(point, z=float64(min_value=0)), ...). Note that in actual code I'd pull out a positive_altitude_point variable for easier reference!
>
> So: adaptability first by composition and second by customisation, but never at the expense of the default case because that's where everyone will start, and where most time will be spent.

 1. I totally agree. The first use case for `rospbt` will be to assert property "node alive" anyway which will not require customization at all. I will implement the composite strategies with 1-level depth leaf strategies according to your proposed design.
 2. After checking out the `builds()` [docs](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.builds) and [source](https://hypothesis.readthedocs.io/en/latest/_modules/hypothesis/strategies.html#builds) I (hope that I) understand how `builds()` helps and why one cannot do better :wink: . And how I actually "Provide some easy ways to compose them" is done with 3. ...
 3. Something similar to [`hypothesis/extra/numpy.ps from_dtype()`](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/numpy.py#L36) I guess. Ok, I understand how 3. helps in 2. now.

Thx for your time... again :+1:

**Comment by Zac-HD** [comment]
I actually removed the versioned docs recently, because there were so many links that it broke the rtd styling (oops!). We won't put docs online for 1.x or 2.0, (libraries.io suggests that almost everyone is using Hypothesis 3) but once 4.x is out we'll leave the last 3.x docs up for a good length of time to enable an orderly transition.  I'd recommend just linking to the latest version though! 

All the rest sounds great and I'm glad I could help :smile:

**Comment by fkromer** [comment]
> I actually removed the versioned docs recently, because there were so many links that it broke the rtd styling (oops!).

I can imagine :wink:

> I'd recommend just linking to the latest version though!

:thumbsup:

> All the rest sounds great and I'm glad I could help 😄

Thx a lot Zac.
